version: "3.8"
services:

  node-01:
    container_name: node-01
    build:
      context: .
    command:
      - "node-01"
    expose:
      - "6223"
    environment:
      - ALIVER_ENV=production
      - ALIVER_CONFIG_PATH=/etc/aliver/config.yml
    networks:
      - aliver

  node-02:
    container_name: node-02
    build:
      context: .
    command:
      - "node-02"
    expose:
      - "6223"
    environment:
      - ALIVER_ENV=production
      - ALIVER_CONFIG_PATH=/etc/aliver/config2.yml
    networks:
      - aliver

networks:
  aliver:
    driver: bridge