cluster_id: 'cluster'
instance_id: '1'
timeout: '5s'

servers:
  - id: '1'
    ip: 'node-01'
    port: 6223
  - id: '2'
    ip: 'node-02'
    port: 6223

check_script: 'scripts/check.sh'
check_interval: '5s'
check_retries: 5
check_timeout: '10s'

run_script: 'scripts/run.sh'
run_timeout: '10s'

stop_script: 'scripts/stop.sh'
stop_timeout: '10s'